# Method header constants
UPLOAD = 'u'
DOWNLOAD = 'd'

DOWNLOAD_CODE = 0
UPLOAD_CODE = 1
# Filename header
FILENAME = 'Filename'

# Package headers
LAST_PACKAGE_INDEX = 0
SEQUENCE_NUMBER_INDEX = 1

# Other stuff
BUFFER_SIZE = 1024
#BUFFER_SIZE = 2048
TIMEOUT_SECS = 1
MAX_RETRIES = 3
FORMAT = 'utf-8'
PAYLOAD_SIZE = 512

PACKAGE_AMOUNT_OF_FIELDS = 3
WINDOW_SIZE = 5