#!/bin/sh
python3 upload-go-back-n.py -H localhost -p 8888 -n test1 -s client_files -v
python3 upload-go-back-n.py -H localhost -p 8888 -n test2 -s client_files -v
python3 upload-go-back-n.py -H localhost -p 8888 -n test3 -s client_files -v
python3 upload-go-back-n.py -H localhost -p 8888 -n test4 -s client_files -v
python3 upload-go-back-n.py -H localhost -p 8888 -n test5 -s client_files -v
